app:
  name: otus-hello
  secretName: app-secret
  configmapName: app-configmap
  portNumber: 8000
  ingressHost: arch.homework
  image: task-db:v5
  profile: kuber
  resources:
    limits:
      cpu: "1"
      memory: "1000Mi"
    requests:
      cpu: "0.1"
      memory: "100Mi"
db:
  pgUsername: otus
  password: b3R1cw==
  port: 5432
postgresql:
  primary:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics/cluster"
      prometheus.io/port: "9000"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  auth:
    username: "otus"
    database: "otus"
    existingSecret: pg-secret
    enablePostgresUser: false
  persistence:
    size: 1Gi
    enabled: false
  image:
    debug: true
  fullnameOverride: myapp-pg
  volumePermissions:
    enabled: true

metrics:
  serviceMonitor:
    enabled: true